"""added breed column

Revision ID: 434dadda573b
Revises: 
Create Date: 2023-07-20 15:30:42.134058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434dadda573b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('breed', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'breed')
    # ### end Alembic commands ###
